name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up zip utility
        run: sudo apt-get install -y zip

      - name: Build CLI zip package
        run: |
          mkdir -p dist
          zip -r dist/jamf-ddm-sofa-cli.zip bin install.sh man README.md LICENSE

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: dist/jamf-ddm-sofa-cli.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
